# Generated by Django 4.1.1 on 2022-09-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='img',
            field=models.ImageField(default='', upload_to='fruit/images'),
        ),
    ]
